### ISSUE TITLE
npm install fails for client App 

### ISSUE THREAD

**Issue by gunjank** [souravbh/mockProxyServer#1]
Running `npm install` on mockProxyServer/mockProxyClient but getting below error. How to run client app ? 

no such file or directory, open '/mockProxyServer/mockProxyClient/node_modules/.staging/@babel/polyfill-f91d0e89/scripts/prepublish.js

**Comment by souravbh** [comment]
What is the node version?

**Comment by gunjank** [comment]
v8.11.2

**Comment by souravbh** [comment]
Updated the readme, rebase the code, run the quick start.
