### ISSUE TITLE
Tried to mock request input field with dynamic matcher values and got below error 

### ISSUE THREAD

**Issue by gunjank** [souravbh/mockProxyServer#4]
Tried to mock request input field with dynamic matcher values and got below error 
{
    "timestamp": 1551395507877,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "org.junit.ComparisonFailure",
    "message": "expected:<[example glossary]> but was:<[abc]>",
    "path": "/mock/v1/someapi"
}

**Comment by souravbh** [comment]
Updated the modeller. Please rebase the server and check..
